query GetDrugs($input: DrugsGetInput!) {
  drugs(input: $input) {
    nodes {
      _id
      createdAt
      name
      stock
    }
    pageInfo {
      currentPage
      hasNextPage
      perPage
      total
    }
  }
}
