query Viewer {
  viewer: me {
    ... on Admin {
      _id
      email
      name
      userType
      image
    }
    ... on User {
      _id
      email
      name
      userType
      image
    }
  }
}
