services:
  drug-Store-Panal:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: Drug-Store-Panal
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
